#!/bin/bash

# This script is run by crontab every day to commit all changes to the
# repository.

# PATH_TO_REPO will be replaced by the script with the actual path
cd PATH_TO_REPO
git add -A
git commit -m "Automatic daily commit"
git push origin master
