#!/bin/bash

# This script is run by crontab every day to commit all changes to the
# repository.

# PATH_TO_REPO will be replaced by the script with the actual path
cd PATH_TO_REPO
/usr/bin/git add -A
/usr/bin/git commit -m "Automatic daily commit"
/usr/bin/git push origin master
